# Used to trigger self-push CI
name: Self-hosted runner (push-caller)

on:
  pull_request:

jobs:

  run_push_ci:
    name: Trigger Push CI
    runs-on: ubuntu-22.04
    steps:
      - name: Trigger push CI via workflow_run
        run: echo "Trigger push CI via workflow_run"
