name: 'PR Triage'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  validate-title:
    name: Validate title
    # if: github.event.action != 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - name: Validate pull request title
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          REGEX="^(revert: )?(feat|fix|docs|style|refactor|perf|test|workflow|build|ci|chore|types|wip)(\\(.+\\))?: .{1,72}$"

          echo "Title: \"$TITLE\""

          if [[ ! "$TITLE" =~ $REGEX ]]; then
            exit 1
          fi
